### ISSUE TITLE
[Question] How about FSRCNN?

### ISSUE THREAD

**Issue by 2ji3150** [nagadomi/waifu2x#188]
The authors of SRCNN have published another paper about accelerating SRCNN(FSRCNN).now it can run in real-time performance .

http://mmlab.ie.cuhk.edu.hk/projects/FSRCNN.html

Does this paper helpful for waifu2x for better quality and performance?

**Comment by nagadomi** [comment]
That architecture is similar to current waifu2x model(upconv_7) but more smaller.
It is pretty fast, but the quality(PSNR) is low, I guess.

**Comment by ABDOELSHEMY** [comment]
yeah ،but the quality still very good ،and the speed much much faster ،it is ahuge improvment speed ،please @nagadomi that would be great and very important if you get some time to look on this ،it is deserve that .thanks alott.

**Comment by Mickevincent** [comment]
I agree. This is a nice step towards Waifu2x in real time.

**Comment by chungexcy** [comment]
@ABDOELSHEMY @Mickevincent If you are familiar with MadVR, which is a DirectShow video renderer for most media player like MPC-HC, the author introduced a real-time algorithm called NGU(Next Gen Upscaling) since last year. On a mid-end GTX 960, it reach high preset for doubling 1080p 24fps to 4k in real-time.

The quality is higher FSRCNN and slightly lower than waifu2x, based on the author's claim on forum. I personally believe that is a CNN based algorithm.

I believe waifu2x would prefer to offer a better quality when the time is not sensitive.

**Comment by Mickevincent** [comment]
@ chungexcy 
Thank you. I am not familiar with MadVR. What I am after is for ps1 emulation first and foremost. Then we are talking about upscaling images around 320x240 up to at least 1080. I guess this would be very possible then with my 980ti. Of course, someone would have to port this as a shader to, for example, Retroarch. Is it possible to first test this algorithm somewhere?

**Comment by chungexcy** [comment]
@Mickevincent
I'm not familiar with ps emulator. Regarding to 4x of 320x240, with cudnn, 980ti is potentially able to reach about 30fps using upconv twice. But cudnn should not be included in any distribution.
As for MadVR, unfortunately, the model is not public outside of the render. But if you treat your output as a YUV video stream and send it to MadVR directly or to media player as a live stream, you should be able to utilize it. BTW, MadVR has an anti-aliasing version of NUG, which is optimized for pixel art style of image.

**Comment by ABDOELSHEMY** [comment]
@ chungexcy
Thank you ,yes I am tottly familiar with MadVR ,and madshi do great gob on it , Especially the magic of NGU ,the only big diffrent betwen waifu2x and NGU is the denois ,waifu2x in 2d Anime can tottly clean low bitrate compresing artifacts ,but much much much slower than ngu, i am send to 
 madshi about that Since a week and hope he get some time to look in the some comparison images.

**Comment by Heiseikiseki** [comment]
https://github.com/igv/FSRCNN-TensorFlow

More Informations
