### ISSUE TITLE
Error missing transparent

### ISSUE THREAD

**Issue by thiennx-nws** [nagadomi/waifu2x#241]
I was using waifu to scale image but I have a trouble.
When I scale an image transparent it will transform to the image have background white.
![5b29c290-c788-4a04-a201-06b2ac1f112d](https://user-images.githubusercontent.com/33272256/41898519-6d8c86f4-7954-11e8-826c-92325912134a.png)
![5b31f3438c269-1530000195](https://user-images.githubusercontent.com/33272256/41898530-75a02698-7954-11e8-888b-b542e6716b0a.png)
Thank for your support

**Comment by nagadomi** [comment]
The image is Bilevel Format (each pixel is represented by 1-bit). It is not supported because we cannot interpolate pixel values.
We can support the alpha channel of Bilevel image, but the output image will be 8-bit grayscale.
If you convert the image to 8-bit grayscale(with alpha channel) before input to waifu2x, it will work.
