### ISSUE TITLE
[train] How do you make the lines clear?

### ISSUE THREAD

**Issue by xldsdr124** [nagadomi/waifu2x#371]
![test1](https://user-images.githubusercontent.com/26106045/100430756-28c1ff80-30d2-11eb-8227-0e09903961e8.png)
（use my_cunet noise3_scale2.0x_model)

![test2](https://user-images.githubusercontent.com/26106045/100431094-a38b1a80-30d2-11eb-8478-d702800df97e.png)
(use cunet noise3_scale2.0x_model)

The pre-trained cunet has clearer lines. Does it contain any special training samples?

**Comment by nagadomi** [comment]
I'm not sure, but it may be due to different training datasets.
The main image dataset is a collection of art images, such as those posted on pixiv or danbooru. It has clear contour lines. Anime capture image not included. 
Also adding some artificial data. dot images( https://github.com/nagadomi/waifu2x/issues/356#issuecomment-685111347 ), and novel images.
![8a04b102b2ed534900e6cf0ae522f89d](https://user-images.githubusercontent.com/287255/100443169-86634580-30ec-11eb-8b5d-afed7c2ff825.png)
The novel image was generated by randomizing the font size and color from Aozora Bunko  (public domain japanese digital library).

**Comment by xldsdr124** [comment]
> I'm not sure, but it may be due to different training datasets.
> The main image dataset is a collection of art images, such as those posted on pixiv or danbooru (filtered by PNG format). It has clear contour lines. Anime capture image not included.
> Also adding some artificial data. dot images( [#356 (comment)](https://github.com/nagadomi/waifu2x/issues/356#issuecomment-685111347) ), and novel images.
> ![novel image](https://user-images.githubusercontent.com/287255/100443169-86634580-30ec-11eb-8b5d-afed7c2ff825.png)
> The novel image was generated by randomizing the font size and color from Aozora Bunko (public domain japanese digital library).

Thanks, I may need more resources for training.
