### ISSUE TITLE
when i ws going to download pic in this demo webiste, it told me dowload error 

### ISSUE THREAD

**Issue by Hurricane-k** [nagadomi/waifu2x#407]
I just wanna ask if the demo website cant work well, I found it cant convert pic and cant downlaod the pic, i dont know how to deal with, and i dont find anything about fixing this problems in current issues.

**Comment by nagadomi** [comment]
It does work, but sometimes the server is down(#197). When the server is under heavy load, requests to specify URL often fail due to timeout. In that case, download the image yourself and upload it to the demo website to avoid errors.
If you are using Firefox browser, you can press the `CTRL+S` key to save image. `Save Image` menu doesn't work.
What kind of error do you get?

**Comment by Hurricane-k** [comment]
i dont use Linux, and i just open this website on google chrome on win10. sometimes it shows Sever Error and dont have any more detailed infomationn and sometimes it shows "403 DOMAIN NOT FOUND IN WHITELIST"

**Comment by nagadomi** [comment]
>sometimes it shows Sever Error

Does it sometimes work fine? Then it is due to the server load. There are no plans to support it.

>403 DOMAIN NOT FOUND IN WHITELIST

It may be an error due to censorship from your Internet provider or home network.
Or it could be an error related to reCAPTCHA, but I've never encountered it.

**Comment by Hurricane-k** [comment]
> > sometimes it shows Sever Error
> 
> Does it sometimes work fine? Then it is due to the server load. There are no plans to support it.
> 
> > 403 DOMAIN NOT FOUND IN WHITELIST
> 
> It may be an error due to censorship from your Internet provider or home network.
> Or it could be an error related to reCAPTCHA, but I've never encountered it.

ok i need to try later
